honey: https://chromewebstore.google.com/detail/honey-automatic-coupons-r/bmnlcjabgnpnenekpadlanbbkooimhnj/reviews?hl=en
coupert: https://chromewebstore.google.com/detail/coupert-automatic-coupon/mfidniedemcgceagapgdekdbmanojomk/reviews?hl=en
avast: https://chromewebstore.google.com/detail/avast-safeprice-compariso/eofcbnmajmjmplflapaojjnihcjkigck/reviews?hl=en
aliexpress: https://chromewebstore.google.com/detail/aliexpress-coupon-finder/adanomdlalebngcphfbknoglbcdcbchb/reviews?hl=en
pricehistory: https://chromewebstore.google.com/detail/price-history-tracker-aut/ojplmecpdpgccookcobabopnaifgidhf/reviews?hl=en
cently: https://chromewebstore.google.com/detail/cently-automatic-coupons/kegphgaihkjoophpabchkmpaknehfamb/reviews?hl=en
couponbirds: https://chromewebstore.google.com/detail/couponbirds-smartcoupon-c/pnedebpjhiaidlbbhmogocmffpdolnek/reviews?hl=en
fatcoupon: https://chromewebstore.google.com/detail/fatcoupon-cash-back-promo/cakejefemdjbmhdjkjhibjhmhgjefidm/reviews?hl=en

